." TOPIC: ddh(1)
." AUTHOR: dd86k <dd@dax.moe>
."
." Please read man-pages(7) and groff_man(7) about the manual page format.
." If you're missing groff_man.7, install groff. Solid documentation.
."
.TH ddh 1 "April 2022" dd86k "User manual"
.SH NAME
ddh \(em Generic hasher

.SH SYNOPSIS
.SY ddh
.B  {list|ver|help|version|license|HASH}
.SY ddh
.B  HASH
.OP options...
.B  {files|-}...
.YS

.SH DESCRIPTION
.B ddh
is a generic hasher. The main goal of this utility is to centralize
the various options into one package for multiple systems.

By default, the GNU-style checksums are used. You can use
.B --tag
to switch to the BSD-style checksums. This affects reading lists.

There is also
.B --sri
for a Sub-Resource Integrity style hash. This is not supported in lists.

The default entry mode is File for being the best case scenario for
behaving better on zero-length files, network shares, and on most
operating systems. The Mmfile option is good for performance reasons.

.SH EXAMPLES

.TP
.BI ddh \ help
Shows help screen and exit.

.TP
.BI ddh \ version
Shows version screen and exit.

.TP
.BI ddh \ list
List supported checksum and hash algorithms and exit.

.TP
.BI echo\ "test"\ |\ ddh \ sha1
Use SHA-1 to read from the standard input file handle and digest a result.

.TP
.BI ddh\ sha3-256 \ essay.txt
Use SHA-3-256 to hash
.I essay.txt
.R .

.TP
.BI ddh\ sha256 \ src/*
Use SHA-256 to hash all files in the
.I src
folder.

.TP
.BI ddh\ md5 \ -Ms \ "*.{json,md}"
Use MD5 to hash all files in sub-directories
.RI ( -s )
that end with .json or .md using the memory-mapped file option
.RI ( -M )
using the embedded glob matcher.

.TP
.BI ddh\ sha256 \ -c\ list
Use SHA-256 to verify the integrity a list of files. This is similar to
.BR sha256sum\ -c\ list .

.SH ALIASES

Below is a list of supported checksum and hash algorithms.

." See tbl(1)




.TS
l l l.
Alias	Name	Tag
.T&
lB l l.
_
crc32	CRC-32	CRC32
crc64iso	CRC-64-ISO	CRC64ISO
crc64ecma	CRC-64-ECMA	CRC64ECMA
md5	MD5-128	MD5
ripemd160	RIPEMD-160	RIPEMD160
sha1	SHA-1-160	SHA1
sha224	SHA-2-224	SHA2-224
sha256	SHA-2-256	SHA2-256
sha384	SHA-2-384	SHA2-384
sha512	SHA-2-512	SHA2-512
sha3-224	SHA-3-224	SHA3-224
sha3-256	SHA-3-256	SHA3-256
sha3-384	SHA-3-384	SHA3-384
sha3-512	SHA-3-512	SHA3-512
shake128	SHAKE-128	SHAKE-128
shake256	SHAKE-256	SHAKE-256
blake2b512	BLAKE2b-512	BLAKE2B-512
blake2s256	BLAKE2s-256	BLAKE2S-256
mmhash3-32	MurmurHash3-32	MURMURHASH3-32
mmhash3-128	MurmurHash3-128	MURMURHASH3-128
.TE

.SH OPTIONS

Short options can be combined. Options that expect an additional argument
(i.e., the following argument) should not be combined, this includes
.I -c
and
.IR -a .

.SS Entry methods
.TS
l l.
Option	Description
.T&
lB l.
-a, --arg	Hash argument text as UTF-8.
-c, --check	Check hashes against a file.
-C, --compare	Compare all files.
-A, --againt	Check hashes against this hash.
--stdin	Set input mode to stdin.
.TE

.SS File input modes
.TS
l l.
Option	Description
.T&
lB l.
_
-F, --file	Set input mode to file (default).
-b, --binary	File: Set read mode to binary (default).
-t, --text	File: Set read mode to text.
-M, --mmfile	Set input mode to memory-mapped file.
.TE

.SS Embedded globber engine
.TS
l l.
Option	Description
.T&
lB l.
_
--shallow	Same-level directory (default).
-s, --depth	Deepest directories first.
--breath	Sub directories first.
--follow	Follow symbolic links (default).
--nofollow	Do not follow symbolic links.
.TE

.SS Miscellaneous
.TS
l l.
Option	Description
.T&
lB l.
_
--gnu	Create or read GNU-style hashes. (default)
--tag	Create or read BSD-style hashes.
--sri	Create SRI-style hashes.
-B, --buffersize	Set real buffer size for file/mmfile/stdin (default=4K).
--	Stop parsing arguments.
.TE

.SH WARNINGS

The murmurhash3 hash may be in a different orientation on big-endian machines,
because it has only been tested on a x86-64 machine. If this is the case,
open up an Issue on the GitHub tracker.

.SH NOTES

UNIX-like shells use their own globbing mechanism. To use the embedded
globbing mechanism, use '*' or \\*. You can disable it with the --
switch.

Release versions of this utility has the druntime GC command-line
interface disabled.

HMAC is not supported.

.SH AUTHOR
Written by dd86k
.MT dd@dax.moe
.ME .

.SH LICENSE

ddh is currently licensed under the public domain, and so is this document.